### ISSUE TITLE
Package as gem?

### ISSUE THREAD

**Issue by pyrareae** [vaiorabbit/ruby-imgui#2]
This and [your nuklear binding](https://github.com/vaiorabbit/ruby-nuklear) would be really useful packaged as gems instead of stand-alone projects so that they could be used like any other gui library gem.

**Comment by vaiorabbit** [comment]
Thank you for commenting.

Unfortunately, I don't have time and motivation to maintain gems that include pre-built `imgui.{dll|so|dylib}`. So one possible approach is to:
* make another ImGui gem that is entirely written in C, and
* make users build the Ruby C extension library with their favorite compiler (mingw, gcc, clang, etc.).

This approach is similar to the one I adopted to distribute my rmath3d ( https://rubygems.org/gems/rmath3d , https://github.com/vaiorabbit/rmath3d ) and opengl-bindings_c ( https://rubygems.org/gems/opengl-bindings_c , https://github.com/vaiorabbit/ruby-opengl_c ).

So someday in the future you might be able to get a gem called `ruby-imgui_c`, but please don't get your hopes up ;-)

**Comment by vaiorabbit** [comment]
It's still experimental though, now imgui-bindings gem is available and it contains binaries for both Windows and macOS.
* https://rubygems.org/gems/imgui-bindings
