### ISSUE TITLE
`rescue in block in dlload': can't load C:/Users/user/ruby-imgui/sample/GLFW3.dll

### ISSUE THREAD

**Issue by OkiStuff** [vaiorabbit/ruby-imgui#3]
Hello, Im trying to setup ruby-imgui.. and I have glfw compiled and ready. I also have cimgui ready. I go to do ruby test_glfw_opengl2.rb and it says `rescue in block in dlload': can't load C:/Users/user/ruby-imgui/sample/GLFW3.dll. GLFW3.dll is in the sample folder.. what could be the problem?

**Comment by vaiorabbit** [comment]
*   Please share your situation more precisely (command line history, current directory, etc.)
*   GLFW.load_lib takes library name and path to the glfw3.dll as its arguments. So passing appropriate arguments to this function might solve your problem.
    *   https://github.com/vaiorabbit/ruby-opengl/blob/master/lib/glfw.rb#L492
