### ISSUE TITLE
Fiddle support - a rather technical question.....

### ISSUE THREAD

**Issue by samuelintheforest** [vaiorabbit/ruby-imgui#4]
Hello!

I've tried this wrapper and it is awesome! Thank you very much for it! Although, I could not bundle this 'gem' into my rubyc compilled app.exe, since ffi is not a standard gem and It fails at the compillation due to ffi is a C ext gem (see rubyc...). Never mind, in short, I can only use fiddle but not ffi.... 😥. 
I saw that you've already dealt with both tool (fiddle, and ffi), and I would be so curious about whether there are any chance rewriting ImGui wrapper in fiddle? I've already solved the string pointers using fiddle in imgui-opengl.rb and imgui-glfw.rb, but - logically - I'm struggling with the imgui.rb conversion proccess.... Do you have any suggestion? I would be intrested in how to pass a struct as a struck's element in fiddle. (Like what you did with the FFI..by_value function)

**Comment by vaiorabbit** [comment]
Hello. [Today I looked into Fiddle](https://github.com/vaiorabbit/FiddleTest) for the first time in several years.

Though [the development team are developing actively](https://github.com/ruby/fiddle/blob/ca5e6a040429172949cc3d6987996807a72723c7/NEWS.md), there's still no way to declare passing function arguments of struct instance by value (FFI's `by_value`). According to [their document](https://docs.ruby-lang.org/ja/latest/class/Fiddle=3a=3aFunction.html#S_NEW), all the constants we can use to specify the types of arguments and return types are as follows:

*   Fiddle::TYPE_VOID
*   Fiddle::TYPE_VOIDP
*   Fiddle::TYPE_CHAR
*   Fiddle::TYPE_SHORT
*   Fiddle::TYPE_INT
*   Fiddle::TYPE_LONG
*   Fiddle::TYPE_LONG_LONG
*   Fiddle::TYPE_FLOAT
*   Fiddle::TYPE_DOUBLE
*   Fiddle::TYPE_INTPTR_T
*   Fiddle::TYPE_UINTPTR_T
*   Fiddle::TYPE_PTRDIFF_T
*   Fiddle::TYPE_SIZE_T
*   Fiddle::TYPE_SSIZE_T

This means there's no chance for Fiddle users to wrap many ImGui APIs that accept/return ImVec2 by value. For example:

*   https://github.com/ocornut/imgui/blob/v1.83/imgui.h#L574

```c++
IMGUI_API bool ColorButton(const char* desc_id, const ImVec4& col, ImGuiColorEditFlags flags = 0, ImVec2 size = ImVec2(0, 0));
```

*   https://github.com/ocornut/imgui/blob/v1.83/imgui.h#L341

```c++
IMGUI_API ImVec2 GetWindowPos();
```

So, 

> there are any chance rewriting ImGui wrapper in fiddle?

Unfortunately, no. It seems current Fiddle lacks in the feature corresponding FFI's `by_value`. This limitation of Fiddle makes it hard for us to create a wrapper library for common C/C++ libraries. Without FFI's `by_value` feature, it was impossible to create libraries below:

*   https://github.com/vaiorabbit/sdl2-bindings
*   https://github.com/vaiorabbit/ruby-bgfx
*   https://github.com/vaiorabbit/ruby-nuklear

> Do you have any suggestion?

I haven't used [rubyc](https://github.com/pmq20/ruby-packer) though, according to [the document](https://github.com/pmq20/ruby-packer/blob/677baf238fe4aae9108b29cb16ddb76d14695960/README.md):

> Native C extensions are fully supported

I guess it's better to investigate the reason why we cannot bundle libffi with this packer program.

**Comment by samuelintheforest** [comment]
Hmm, That's interesting. Recently I've found a relatively 'new'  article (from 2015) about the basic usage of fiddle. (The link : [fiddle usage](https://www.honeybadger.io/blog/use-any-c-library-from-ruby-via-fiddle-the-ruby-standard-librarys-best-kept-secret/)) and in that there was an example where she managed to add a struct pointer as an argument in the function definition (the `#extern` command in fiddle). Here is that code snippet: 

Struct definition: (with the extendment of `Fiddle::Importer`)
```
Termios = struct [
  'tcflag_t c_iflag',
  'tcflag_t c_oflag',
  'tcflag_t c_cflag',
  'tcflag_t c_lflag',
  'cc_t         c_cc[20]',
  'speed_t  c_ispeed',
  'speed_t  c_ospeed',
] 
```
and the function definitions
```
  extern 'int   tcgetattr(int, struct termios*)'       # get the config for a serial device
  extern 'int   tcsetattr(int, int, struct termios*)'  # set the config for a serial device
  extern 'int   tcflush(int, int)'
```

in these you can notice a `struct termios*` parameter. So with that bearing in mind, It may be possible, but I'm not sure... Anyway, thank you for your suggestion. 

PS: rubyc, well supports fully native extensions (that means msvc compilled gems in windows) and they are like 1 out of 1000 often c ext gem.. hehe, but not mingw32-64. So actually at the end of the day, it doesn't really support anything c extensions really.... 😒.

PPS: One more thing, I used your glfw wrapper as an example to wrap stb-image.h file. It works properly for me If you want check out my repo: [stbimage](https://github.com/samuelintheforest/stbimage-ruby)

**Comment by vaiorabbit** [comment]
> she managed to add a struct pointer as an argument in the function definition

```c
  int tcgetattr(int, struct termios*);
  int tcsetattr(int, int, struct termios*);
```

These 2 functions require the *POINTER* to the struct `termios`, not the `termios` instance itself.

[When Fiddle's `cparser.rb` encounters "\*" while parsing arguments, it will simply map the type into `Fiddle::TYPE_VOIDP` (== void* in C/C++)](https://github.com/ruby/fiddle/blob/v1.0.8/lib/fiddle/cparser.rb#L238-L239).

If the signature of the function had been something like the following, the author of the article would have failed to wrap the function.

```c
  int tcgetattr(int, struct termios);
  int tcsetattr(int, int, struct termios);
```

If you want to check the behavior of the parser, run the script below:

```ruby
require 'fiddle'
require 'fiddle/cparser'

include Fiddle
include Fiddle::CParser

pp parse_signature('int   tcgetattr(int, struct termios*)')
pp parse_signature('int   tcgetattr(int, void*)')
pp parse_signature('int   tcgetattr(int, FOOBARBAZ*)')
begin
  pp CParser.parse_signature('int   tcgetattr(int, struct termios)')
rescue DLError => e
  pp e
end

# (Result)
# ["tcgetattr", 4, [4, 1]]
# ["tcgetattr", 4, [4, 1]]
# ["tcgetattr", 4, [4, 1]]
# #<Fiddle::DLError: unknown type: struct>
```

The meaning of these numbers are as follows (Ref.: https://github.com/ruby/fiddle/blob/v1.0.8/ext/fiddle/fiddle.h#L108-L111) :
* 4 == Fiddle::TYPE_INT
* 1 == Fiddle::TYPE_VOIDP

On the contrary, the functions in ImGui require the *INSTANCE* of `ImVec2`, not the pointer to the `ImVec2`. 

```c++
// ImVec2 size : the insntace of ImVec2, not a pointer to ImVec2.
IMGUI_API bool ColorButton(const char* desc_id, const ImVec4& col, ImGuiColorEditFlags flags = 0, ImVec2 size = ImVec2(0, 0));
// Returens the insntace of ImVec2, not a pointer to ImVec2.
IMGUI_API ImVec2 GetWindowPos();
```

As I mentioned before, Fiddle cannot handle this situation but Ruby/FFI provides `FFI::Struct.by_value` to explicitly write the argument type where we need to pass the instance of struct.

**Comment by samuelintheforest** [comment]
Okay I got it. Then the only way is to somehow bundle ffi into the packer and then pack it.
