### ISSUE TITLE
lib paths on linux

### ISSUE THREAD

**Issue by incompetentcoder** [vaiorabbit/ruby-imgui#5]
Hello.
The setup for opengl uses hardcoded paths on linux which are not "standard" on all distributions sadly, most have recently switched to abolishing the subdirectories like x86_64-linux-gnu or some have their libs installed themselves in /usr/local/lib.
The default library paths can be found via ld --verbose | grep -o SEARCH_DIR[^\;]* for example. Ideally it would try all of them sequentially and use the first one it finds. I am sadly not aware of any Ruby way to query that.
The only thing i can think of is doing something like:
Dir.glob("/usr/l*/**/libglfw.so") for example to get the actual path to an existing libglfw.so

**Comment by vaiorabbit** [comment]
Normally users *must* give `load_lib` valid paths to shared libraries. You can use without feeding any paths only if you are lucky enough.
I'm sorry to say It's not my task to search around unknown paths in unknown environment that I do not own.

The `discover` methods found in Mittsu may help.
* https://github.com/danini-the-panini/mittsu/blob/337e4d016f9bab99f2d74758b9e4fcd226a790d9/lib/mittsu/renderers/generic_lib.rb

**Comment by incompetentcoder** [comment]
Oh i see mittsu actually does use Dir.glob thing I posted heh ^^ Sorry if that came across wrong, I didn't mean you should have to "fix" this or search for things, would just maybe be an option to put it in the readme or whatever how to find it or to the mittsu discover. Cheers o/
